app/urls.py
from django.urls import path
from app import views

#se utiliza para especificar la url app:..., en base.html
app_name = 'app'

urlpatterns = [
    path('', views.mi_vista, name='app'),
    path('nosotros/', views.nuestra_vista, name='nosotros'),
    
    # juegos con vistas
    
    path('juegos/', views.lista_juegos, name='consultar_juegos'),
    
    # juegos con CBV(clases basadas en vistas)
    
    path('juegos/crear/', views.CrearJuego.as_view(), name='alta_juego'),
    path('juegos/<int:pk>/', views.MostrarJuego.as_view(), name='mostrar_juego'),
    path('juegos/<int:pk>/eliminar/', views.EliminarJuego.as_view(), name='eliminar_juego'),
    path('juegos/<int:pk>/modificar/', views.ModificarJuego.as_view(), name='modificar_juego'),
    
    
    

    
]

proyecto_coder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView

#se utiliza para especificar la url users:..., en base.html
app_name = 'users'

urlpatterns = [
    
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registro/', views.registro, name='registro'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),
    #path('cambio-contrasenia/', views.CambioContrasenia.as_view(), name='cambio_contrasenia'),   
    path('cambio-contrasenia/', views.cambiar_contrasenia, name='cambio_contrasenia'), 
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField 

# Create your models here.

class InformacionExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    descripcion = RichTextField(blank=True)
    
    def __str__(self):
        return self.user.username
    

    
    
    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from ckeditor.fields import RichTextFormField
from django.contrib.auth.forms import PasswordChangeForm



class FormularioCreacion(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)
    
    
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']
        help_texts = {k: '' for k in fields}
        
class EdicionDatosUsuario(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre', max_length=20)
    last_name = forms.CharField(label='Apellido', max_length=20)
    descripcion= RichTextFormField(required=False)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'avatar', 'descripcion'] 
        
        
    
class FormularioCambioContrasenia(forms.Form):
    contrasenia_nueva = forms.CharField(label='Contraseña nueva', widget=forms.PasswordInput)
    repetir_contrasenia = forms.CharField(label='Repetir contraseña', widget=forms.PasswordInput)






    
    
  
                



        

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth import update_session_auth_hash

from users.models import InformacionExtra
from users.forms import FormularioCreacion, EdicionDatosUsuario, FormularioCambioContrasenia



# Create your views here.
def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        
        if formulario.is_valid():
            nombre_usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            usuario = authenticate(username=nombre_usuario, password=contrasenia)
            django_login(request, usuario)
            InformacionExtra.objects.get_or_create(user=request.user)
            return redirect('app:app')
        else:
            return render(request, 'login.html', {'formulario': formulario})
            
    
    formulario = AuthenticationForm()
    return render(request, 'login.html', {'formulario': formulario})

def registro(request):
    
    if request.method == "POST":
        formulario = FormularioCreacion(request.POST)
        
        if formulario.is_valid():
            formulario.save()
            return redirect('users:login')
        else:
            return render(request, 'registro.html', {'formulario': formulario})
            

    formulario = FormularioCreacion()
    return render(request, 'registro.html', {'formulario': formulario})

def perfil(request):
    usuario = request.user
    return render(request, 'perfil.html', {'usuario': usuario})






@login_required
def editar_perfil(request):
    if request.method == "POST":
        formulario = EdicionDatosUsuario(request.POST, request.FILES, instance=request.user)
        
        if formulario.is_valid():
            if 'avatar-clear' in request.POST:
                # Si se selecciona la opción de borrar el avatar
                request.user.informacionextra.avatar.delete()
            elif formulario.cleaned_data.get('avatar'):
                # Si se carga un nuevo avatar
                request.user.informacionextra.avatar = formulario.cleaned_data.get('avatar')            
            request.user.informacionextra.descripcion = formulario.cleaned_data.get('descripcion')
            request.user.informacionextra.save()
            formulario.save()
            return redirect('users:perfil')
        else:
            return render(request, 'editar_perfil.html', {'formulario': formulario})
            
    formulario = EdicionDatosUsuario(initial={'avatar': request.user.informacionextra.avatar, 'descripcion': request.user.informacionextra.descripcion}, instance=request.user)
    return render(request, 'editar_perfil.html', {'formulario': formulario})


@login_required
def cambiar_contrasenia(request):
    if request.method == "POST":
        formulario = FormularioCambioContrasenia(request.POST)
        
        if formulario.is_valid():
            contrasenia_nueva = formulario.cleaned_data.get('contrasenia_nueva')
            repetir_contrasenia = formulario.cleaned_data.get('repetir_contrasenia')
            
            if contrasenia_nueva == repetir_contrasenia:
                request.user.set_password(contrasenia_nueva)
                request.user.save()
                update_session_auth_hash(request, request.user)
                return redirect('users:perfil')
        
        return render(request, 'cambiar_contrasenia.html', {'formulario': formulario})
    
    formulario = FormularioCambioContrasenia()
    return render(request, 'cambiar_contrasenia.html', {'formulario': formulario})





    
    
    


       
    

users/templates/cambiar_contrasenia.html
{% extends 'base.html' %}

{% block title_head %}
    <title>Cambio Contraseña</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Cambio Contraseña</h1>
{% endblock h1_header %}

{% block contenido %}
    <form action="{% url 'users:cambio_contrasenia' %}" method="post">
        {% csrf_token %}
        {% if formulario.contrasenia_nueva.value != formulario.repetir_contrasenia.value%}
            <p style="color: red">La contraseñas ingresadas no son iguales</p>
        {% endif %}
        <table>
            {{ formulario.as_table }}
        </table>
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

users/templates/editar_perfil.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Editar Perfil</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Editar Perfil</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action='' method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario.media}}
        {{formulario}}
    </table>
    <button type='button'><a class="navbar-brand" href={% url 'users:cambio_contrasenia' %}>Cambiar contrasenia</a></button>
    <button>Guardar cambios</button>
</form>
{% endblock contenido %}

users/templates/login.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Inicio de sesion</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Inicio de sesion</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">El usuario o la contraseña es incorrecta</p>
{% endif %}

<form action={% url 'users:login' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Iniciar Sesion</button>
</form>
{% endblock contenido %}

users/templates/logout.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Te deslogueaste con exito!!!</h1>
{% endblock h1_header %}

users/templates/perfil.html
{% extends 'base.html' %}
{% block title_head %}
    <title>Perfil</title>
{% endblock title_head %}

{% block h1_header %}
  <h1>Perfil de {{ usuario.username }}</h1>
{% endblock h1_header %}


{% block contenido %}
<div>
  <table class="table table-hover table-sm table-bordered table-striped">
      <thead>
          <tr>
              <th class="text-center">Perfil</th>
              <th class="text-center">Avatar</th>             
          </tr>
      </thead>
      <tbody>
          <tr>
                
              <th class="text-center">
                  <ul> 
                      <li>Usuario:{{ usuario.username }}</li>
                      <li>Nombre: {{usuario.first_name}}</li>
                      <li>Apellido {{usuario.last_name}}</li>
                      <li>Descripción: {{usuario.informacionextra.descripcion | safe}}</li>
                      <li>Email: {{ usuario.email }}</li>             
                  </ul>
              </th>
              <th class="text-center">
                  {% if usuario.informacionextra.avatar %}
                     <img src={{ usuario.informacionextra.avatar.url }} alt="" height="200px"></p>
                  {% endif %}             
              </th>               
          </tr>
      </tbody>
  </table>
</div>
  <button>
    <a class="navbar-brand" href={% url 'users:editar_perfil' %}>Editar perfil</a>
  </button>
{% endblock contenido %}

  
 

users/templates/registro.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Registro</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Registro</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'users:registro' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrarse</button>
</form>
{% endblock contenido %}