app/urls.py
from django.urls import path
from app import views

#se utiliza para especificar la url app:..., en base.html
app_name = 'app'

urlpatterns = [
    path('', views.mi_vista, name='app'),
    path('nosotros/', views.nuestra_vista, name='nosotros'),
    
    # juegos con vistas
    
    path('juegos/', views.lista_juegos, name='consultar_juegos'),
    
    # juegos con CBV(clases basadas en vistas)
    
    path('juegos/crear/', views.CrearJuego.as_view(), name='alta_juego'),
    path('juegos/<int:pk>/', views.MostrarJuego.as_view(), name='mostrar_juego'),
    path('juegos/<int:pk>/eliminar/', views.EliminarJuego.as_view(), name='eliminar_juego'),
    path('juegos/<int:pk>/modificar/', views.ModificarJuego.as_view(), name='modificar_juego'),
    
    
    

    
]

proyecto_coder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView

#se utiliza para especificar la url users:..., en base.html
app_name = 'users'

urlpatterns = [
    
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registro/', views.registro, name='registro'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),
    #path('cambio-contrasenia/', views.CambioContrasenia.as_view(), name='cambio_contrasenia'),   
    path('cambio-contrasenia/', views.cambiar_contrasenia, name='cambio_contrasenia'), 
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'estandar/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">

                <a class="navbar-brand" href={% url 'app:app' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'app:consultar_juegos' %}>Juegos</a>

                {% if request.user.is_authenticated %}
                    {% if request.user.informacionextra.avatar %}
                        <img src={{request.user.informacionextra.avatar.url}} alt="" height="40px">
                    {% endif %}
                    
                    <a href={% url 'users:perfil' %}>{{request.user.username}}</a>
                                         
                    <a class="btn btn-primary" href={% url 'users:logout' %}>Cerrar sesion</a>
                {% else %}
                    <a class="btn btn-primary" href={% url 'users:login' %}>Inicio sesion</a>
                    <a class="btn btn-primary" href={% url 'users:registro' %}>Registrarse</a>
                {% endif %}

                
            </div>
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header %}
                            <h1 class="mb-5">Estas usando el h1 base</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <!-- Información general breve de la página-->
                            <li class="list-inline-item"><a href={% url 'app:nosotros' %}>Nosotros</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'estandar/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>