app/urls.py
from django.urls import path
from app import views

#se utiliza para especificar la url app:..., en base.html
app_name = 'app'

urlpatterns = [
    path('', views.mi_vista, name='app'),
    path('nosotros/', views.nuestra_vista, name='nosotros'),
    
    # juegos con vistas
    
    path('juegos/', views.lista_juegos, name='consultar_juegos'),
    
    # juegos con CBV(clases basadas en vistas)
    
    path('juegos/crear/', views.CrearJuego.as_view(), name='alta_juego'),
    path('juegos/<int:pk>/', views.MostrarJuego.as_view(), name='mostrar_juego'),
    path('juegos/<int:pk>/eliminar/', views.EliminarJuego.as_view(), name='eliminar_juego'),
    path('juegos/<int:pk>/modificar/', views.ModificarJuego.as_view(), name='modificar_juego'),
    
    
    

    
]

proyecto_coder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/consultar_juegos.html
{% extends 'base.html' %}

{% block title_head %}
<title>Juegos</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Listado de Juegos</h1>
{% endblock h1_header %}


{% block contenido %}
<p>
    <form action={% url 'app:consultar_juegos' %} class="text-center" enctype='multipart/form-data'>
        {{formulario}}
        
        <button>buscar
        </button>
        <button>
            <a class="navbar-brand" href={% url 'app:alta_juego' %}>Agregar</a>
        </button>
        
    </form>
</p>

{% if juegos %}


<!-- Tabla de resutados de busqueda-->
    <div> 
        <table class="table table-hover table-sm table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">Juegos</th>                       
                    <th class="text-center">Especificaciones</th>                 
                    <th class="text-center">Opciones</th>                 
                </tr>
            </thead>
            <tbody>
                {% for juego in juegos %}
                <tr>
                  <td class="text-center">
                    {% if juego.imagen.url and juego.imagen%}
                        <img src={{juego.imagen.url}} alt="" height="80px"> 
                    {% endif %}                             
                  </td>  
                  <td class="text-left">
                    <ul>
                        <li>Nombre: {{juego.nombre}}</li>
                        <li>Desarollo: {{juego.desarrollo}}</li>
                        <li>Dispositivo: {{juego.dispositivo}}</li>
                        <li>Genero: {{juego.genero}}</li>
                    </ul>
                  </td>
                  
                  <td class="text-center">
                    <button>
                        <a class="navbar-brand" href={% url 'app:mostrar_juego' juego.id %}>Mostrar</a>
                    </button>
                    <button>
                        <a class="navbar-brand" href={% url 'app:modificar_juego' juego.id %}>Modificar</a>
                    </button>
                    <button>
                        <a class="navbar-brand" href={% url "app:eliminar_juego" juego.id %}>Eliminar</a>
                    </button>
                  </td>
                </tr>
                {% endfor %}
            </tbody>


        </table>
    </div>

    <div class="paginador">
        <div class="row">

        </div>
    </div>
{% else %}
    <h2 class="text-center">No hay datos sobre juegos por el momento.</h2>
{% endif %}
{% endblock contenido %}

app/templates/index.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Bienvenidos a mi pagina principal</h1>
{% endblock h1_header %}

app/templates/nosotros.html
{% extends 'base.html' %}

{% block title_head %}
                    <title>Nosotros</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Nos dedicados a informar sobre los distintos juegos
                        lanzados en el mercado, con sus especificaciones.
                    </h1>
{% endblock h1_header %}

{% block contenido %}
<h1 class="text-center"> Propiertario: Caliva Ariel
</h1>
{% endblock contenido %}